/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import addschedule.AddSchedule;

/**
 *
 * @author suong
 */
public class ConfirmFrm extends javax.swing.JFrame {

    /**
     * 
     * @param addSchedule 
     */
    public ConfirmFrm(AddSchedule addSchedule) {
        initComponents();
        this.addSchedule = addSchedule;
        this.NameField.setText(addSchedule.getMovie().getMovieName());
        this.RoomField.setText(addSchedule.getRoom().getRoomName());
        this.DateTimeField.setText(addSchedule.getDateTime());
        this.NormalField.setText(String.valueOf(addSchedule.getSeatNormal()));
        this.VipField.setText(String.valueOf(addSchedule.getSeatVip()));
        this.DoubleField.setText(String.valueOf(addSchedule.getSeatDouble()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anoucement = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        RoomField = new javax.swing.JTextField();
        DateTimeField = new javax.swing.JTextField();
        NormalField = new javax.swing.JTextField();
        VipField = new javax.swing.JTextField();
        DoubleField = new javax.swing.JTextField();
        movieNameLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        DateTimeLabel = new javax.swing.JLabel();
        NormalLabel = new javax.swing.JLabel();
        VipLabel = new javax.swing.JLabel();
        DoubleLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        anoucement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anoucement.setText("Vui lòng xác nhận thông tin một lần nữa!");

        NameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        RoomField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DateTimeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NormalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        VipField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DoubleField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        movieNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieNameLabel.setText("Tên Phim");

        roomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomLabel.setText("Phòng Chiếu");

        DateTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateTimeLabel.setText("Thời Gian");

        NormalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NormalLabel.setText("Ghế Thường");

        VipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VipLabel.setText("Ghế Vip");

        DoubleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoubleLabel.setText("Ghế Đôi");

        SubmitButton.setText("Xác Nhận");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ReturnButton.setText("Quay Lại");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NormalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoubleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoubleField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(VipField)
                    .addComponent(NormalField)
                    .addComponent(DateTimeField)
                    .addComponent(RoomField)
                    .addComponent(NameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(anoucement, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(anoucement)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NormalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NormalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VipLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoubleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(ReturnButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        if (addSchedule.Save())
        {
            dispose();
        
            new LoginFrm(new AddSchedule()).setVisible(true);
        }

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new FillPriceTicket(addSchedule).setVisible(true);
    }//GEN-LAST:event_ReturnButtonActionPerformed


    private AddSchedule addSchedule;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateTimeField;
    private javax.swing.JLabel DateTimeLabel;
    private javax.swing.JTextField DoubleField;
    private javax.swing.JLabel DoubleLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NormalField;
    private javax.swing.JLabel NormalLabel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JTextField RoomField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField VipField;
    private javax.swing.JLabel VipLabel;
    private javax.swing.JLabel anoucement;
    private javax.swing.JLabel movieNameLabel;
    private javax.swing.JLabel roomLabel;
    // End of variables declaration//GEN-END:variables
}
