/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import addschedule.AddSchedule;

/**
 *
 * @author suong
 */
public class FillPriceTicket extends javax.swing.JFrame {

    /**
     * Creates new form FillPriceTicket
     */
    public FillPriceTicket(AddSchedule addSchedule) {
        initComponents();
        setLocationRelativeTo(null);
        this.addSchedule = addSchedule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NormalLabel = new javax.swing.JLabel();
        VipLabel = new javax.swing.JLabel();
        DoubleLabel = new javax.swing.JLabel();
        announcement = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        NormalField = new javax.swing.JTextField();
        VipField = new javax.swing.JTextField();
        DoubleField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NormalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NormalLabel.setText("Ghế Thường");

        VipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VipLabel.setText("Ghế Vip");

        DoubleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoubleLabel.setText("Ghế Đôi");

        announcement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announcement.setText("Vui lòng nhấp giá tiền cho mỗi loại ghế!");

        SubmitButton.setText("Xác Nhận");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ReturnButton.setText("Quay Lại");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        NormalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        VipField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DoubleField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NormalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoubleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubmitButton)
                        .addGap(18, 18, 18)
                        .addComponent(ReturnButton)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VipField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NormalField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(announcement, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(announcement)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NormalLabel)
                    .addComponent(NormalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VipLabel)
                    .addComponent(VipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoubleLabel)
                    .addComponent(DoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(ReturnButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        if(!NormalField.getText().equals("") && !NormalField.getText().equals("") && !NormalField.getText().equals(""))
        {
            addSchedule.setSeatNormal(Long.parseLong(NormalField.getText()));
            addSchedule.setSeatVip(Long.parseLong(VipField.getText()));
            addSchedule.setSeatDouble(Long.parseLong(DoubleField.getText()));
            dispose();
            new ConfirmFrm(addSchedule).setVisible(true);
        }
        else
        {
            announcement.setText("Vui lòng điền đầy đủ thông tin!");
        }

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new FillDateTime(addSchedule).setVisible(true);
        
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private AddSchedule addSchedule;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoubleField;
    private javax.swing.JLabel DoubleLabel;
    private javax.swing.JTextField NormalField;
    private javax.swing.JLabel NormalLabel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField VipField;
    private javax.swing.JLabel VipLabel;
    private javax.swing.JLabel announcement;
    // End of variables declaration//GEN-END:variables
}
